defaultSemverRangePrefix: ''

yarnPath: .yarn/releases/yarn-2.4.2.cjs

packageExtensions:
  '@docusaurus/core@*':
    dependencies:
      url: '*'
  'docusaurus-plugin-typedoc@*':
    dependencies:
      progress: '*'
  'react-live@*':
    peerDependencies:
      react: '*'
