version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

executors:
  build_env:
    docker:
      - image: circleci/node:10.15

commands:
  install:
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run:
          name: Install npm Dependencies
          command: npm install --ignore-scripts
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}

jobs:
  lint:
    executor: build_env
    steps:
      - checkout
      - install
      - run: npm run test:lint
  types:
    executor: build_env
    steps:
      - checkout
      - install
      - run: npm run test:types
  spec:
    executor: build_env
    steps:
      - checkout
      - install
      - run: npm run test:spec
      - codecov/upload:
          file: ./coverage/lcov.info
  build:
    executor: build_env
    steps:
      - checkout
      - install
      - run: npm run build
      - run:
          name: Set canary package version
          command: npm version 0.0.0-$(echo $CIRCLE_SHA1 | cut -c -9) --no-git-tag-version
      - run:
          name: Build canary package tarball
          command: |
            npm pack --silent > tarball_name
            mv "$(cat tarball_name)" package.tgz
      - store_artifacts:
          path: package.tgz
      - persist_to_workspace:
          root: ~/project
          paths:
            - package.tgz
  publish_canary:
    executor: build_env
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Authenticate with npm registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
      - run:
          name: Publish canary package
          command: npm publish package.tgz --tag canary

workflows:
  version: 2
  commit:
    jobs:
      - lint
      - types
      - spec:
          requires:
            - lint
            - types
      - build:
          requires:
            - lint
            - types
      - publish_canary:
          requires:
            - spec
            - build
          filters:
            branches:
              only: master
