module.exports = {
  docs: {
    Overview: ['installation', 'typescript', 'comparison'],
    Fundamentals: [
      'connecting-inputs',
      'form-lifecycle',
      'ui-libraries',
      'validation',
    ],
    'Advanced Features': [
      'field-arrays',
      'external-state',
      'masked-inputs',
      'dependent-fields',
      'derived-state',
    ],
    Reference: [
      {
        type: 'link',
        label: 'FormProvider Component',
        href: '/docs/api/variables/formprovider',
      },
      {
        type: 'link',
        label: 'useField Hook',
        href: '/docs/api/functions/usefield',
      },
      {
        type: 'link',
        label: 'useFormStatus Hook',
        href: '/docs/api/functions/useformstatus',
      },
    ],
  },
  API: [{type: 'autogenerated', dirName: 'api'}],
};
